## <b>100 NUMPY EXERCISES</b>

1. Import the numpy package under the name np (★☆☆)

In [4]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.__version__)

1.26.4


In [6]:
print(np.show_config())

{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30153",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.8",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30153",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas64",
      "found": true,
      "version": "0.3.23.dev",
      "detection method": "pkgconfig",
      "include directory": "/c/opt/64/include",
      "lib directory": "/c/opt/64/lib",
      "openblas configuration": "USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= 

3. Create a null vector of size 10 (★☆☆)

In [7]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array (★☆☆)

In [8]:
print("Size of array:", x.size, "\nMemory size of arary:", x.itemsize, "\nMemory size in bytes:", x.size * x.itemsize)

Size of array: 10 
Memory size of arary: 8 
Memory size in bytes: 80


5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In terminal:
1. python -c "help()"
2. numpy.add

In [9]:
# Alternative
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [21]:
z = np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [33]:
a = np.arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element becomes last) (★☆☆)

In [26]:
a_reverse = a[::-1]
a_reverse

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [32]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [38]:
example_array = np.array([1,2,0,0,4,0])
np.where(example_array == 0)


(array([2, 3, 5], dtype=int64),)

11. Create a 3x3 identity matrix (★☆☆)

In [39]:
id_matrix = np.eye(3)
id_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values (★☆☆)

In [48]:
rand_333_matrix = np.random.random((3, 3, 3))
rand_333_matrix

array([[[0.2731173 , 0.30646049, 0.62920428],
        [0.70712347, 0.62254052, 0.56604079],
        [0.31384656, 0.70108073, 0.78770737]],

       [[0.57909608, 0.74190906, 0.96154008],
        [0.67070068, 0.74789768, 0.03239066],
        [0.5397521 , 0.42569305, 0.80026443]],

       [[0.11017133, 0.30029897, 0.64902208],
        [0.67784105, 0.25327989, 0.52278344],
        [0.0930124 , 0.49773038, 0.13782994]]])

13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [50]:
rand_1010_matrix = np.random.random((10, 10))
rand_1010_matrix.min()

0.018164983429563852

In [51]:
rand_1010_matrix.max()

0.9942467326984805

14. Create a random vector of size 30 and find the mean value (★☆☆)

In [54]:
rand_30_array = np.random.random(30)
rand_30_array.mean()

0.511937102169044

15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [66]:
bordered_2darray = np.ones((5, 5))
bordered_2darray[1:-1, 1:-1] = 0
bordered_2darray

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [88]:
add_border = np.zeros((5, 5))
add_border[:, [0, -1]] = 1
add_border[[0, -1], :] = 1
add_border

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

17. What is the result of the following expression? (★☆☆)

- 0 * np.nan
- np.nan == np.nan
- np.inf > np.nan
- np.nan - np.nan
- np.nan in set([np.nan])
- 0.3 == 3 * 0.1

In [91]:
# NaN is "not a number"
0 * np.nan

nan

In [92]:
np.nan == np.nan

False

In [93]:
# inf is "infinity"
np.inf > np.nan

False

In [95]:
np.nan - np.nan

nan

In [96]:
np.nan in set([np.nan])

True

In [103]:
0.3 == 3 * 0.1

False

In [102]:
test = float("{:.1f}".format(3 * 0.1))
test

0.3

In [104]:
0.3 == test

True

In [100]:
3 * 0.1

0.30000000000000004

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [145]:
diagonal = np.zeros((5, 5), dtype=int)
cur = 1
for x in range(1, 5):
    diagonal[x][x-1] = cur
    cur += 1
diagonal


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [144]:
diagonal2 = np.diag(1+np.arange(4),k=-1)
diagonal2

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [113]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
# Translation: [start at index 1 with a step of 2, each row with a step of 2]
checkerboard[::2, 1::2] = 1 
# Translation: [each column with a step of 2, start at index 1 with a step of 2]
checkerboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [157]:
arr1 = np.array(range(1, 6*7*8+1)).reshape(6, 7, 8)
np.where(arr1 == 100)


(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64))

21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

22. Normalize a 5x5 random matrix (★☆☆)

23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

26. What is the output of the following script? (★☆☆)
- print(sum(range(5),-1))
- from numpy import *
- print(sum(range(5),-1))

27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

- Z**Z
- 2 << Z >> 2
- Z <- Z
- 1j*Z
- Z/1/1
- Z<Z>Z

28. What are the result of the following expressions?

29. How to round away from zero a float array ? (★☆☆)

30. How to find common values between two arrays? (★☆☆)